name: brawlde-guessing-game

services:
  backend:
    build: ./backend
    # expose port ONLY, so people can't directly talk to backend
    expose:
      [8000]
  
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend